language: java

jdk:
  openjdk8

services:
  - docker

before_install:
  - chmod +x mvnw
  - sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Teste!@#" -p 1433:1433 --name sql1 -d microsoft/mssql-server-linux 



