language: java
jdk:
  - openjdk8
before_install:
  - chmod +x mvnw

before_script:
  - sudo docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=<Teste!@#>" \
  -p 1433:1433 --name sql1 \
  -d microsoft/mssql-server-linux