language: java

jdk:
  openjdk8

services:
  - docker

before_install:
  - chmod +x mvnw
  - docker pull carlad/sinatra
  - chmod +x docker-compose
  - docker run -d -p 127.0.0.1:80:4567
  - docker ps -a




