sqlserver:
  image: microsoft/mssql-server-linux
  hostname: sqlserver
  environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=Teste123
  ports:
    - 1433:1433

mongo:
  image: mongo
  environment:
    MONGO_INITDB_ROOT_USERNAME: sa
    MONGO_INITDB_ROOT_PASSWORD: Teste123
  ports:
    - "27017:27017"